name: Try Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/setup-node@v3
      name: Setup node
      with:
        node-version: 16.x.x
        cache: npm

    - run: node --version
      name: Check Node Version
    
    - uses: actions/checkout@v3
      name: Checkout code

    - run: yarn
      name: Install NPM Packages
    
    - run: yarn build
      name: Build Project
      
